version: '3'
services:
    proxy:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - '20000:80'
            - '20001:443'
        depends_on:
            - api
        networks:
            - apicontagem-network
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5000:80'
            - '5001:443'
        depends_on: 
            - grpc
        networks:
            - apicontagem-network

    grpc:
        build:
            context: /loggrpc/regGRPC
            dockerfile: Dockerfile
        ports:
            - '5005:5001'
        networks:
            - apicontagem-network
networks:
    apicontagem-network:
        driver: bridge
