version: '3'
services:
    proxy:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - '20000:80'
            - '20001:443'
        depends_on:           
            - grpc            
        networks:
            - apicontagem-network
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/   
    grpc:
        stdin_open: true
        tty: true
        build:
            context: /loggrpc/regGRPC
            dockerfile: Dockerfile        
        networks:
            - apicontagem-network
networks:
    apicontagem-network:
        driver: bridge
